package model;

public class Equipment {
    private int equipmentId;
    private String type;
    private String make;
    private String model;

    // Constructor for new records (ID is auto-generated by the database)
    public Equipment(String type, String make, String model) {
        this.type = type;
        this.make = make;
        this.model = model;
    }

    // Getters and Setters
    public int getEquipmentId() {
        return equipmentId;
    }

    public void setEquipmentId(int equipmentId) {
        this.equipmentId = equipmentId;
    }

    public String getType() {
        return type;
    }

    public String getMake() {
        return make;
    }

    public String getModel() {
        return model;
    }

    // Include setters if modification is necessary after creation
}
