package model;

public class Specialist {
    private int specialistId; // Auto-generated by the database, not needed for insertions
    private String name;
    private String expertiseArea;

    // Constructor without ID for creating new records
    public Specialist(String name, String expertiseArea) {
        this.name = name;
        this.expertiseArea = expertiseArea;
    }

    // Getters and Setters
    public int getSpecialistId() { return specialistId; }
    public void setSpecialistId(int specialistId) { this.specialistId = specialistId; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getExpertiseArea() { return expertiseArea; }
    public void setExpertiseArea(String expertiseArea) { this.expertiseArea = expertiseArea; }
}
