package model;

public class Specialist {
    private int specialistId;
    private String name;
    private String expertiseArea;

    // Constructor for new records (ID is auto-generated by the database)
    public Specialist(String name, String expertiseArea) {
        this.name = name;
        this.expertiseArea = expertiseArea;
    }

    // Getters and Setters
    public int getSpecialistId() {
        return specialistId;
    }

    public void setSpecialistId(int specialistId) {
        this.specialistId = specialistId;
    }

    public String getName() {
        return name;
    }

    public String getExpertiseArea() {
        return expertiseArea;
    }

    // Include setters if modification is necessary after creation
}
